In [1]:
### In this notebook we attempt interpolation of photo-z results.
import numpy as np
from scipy.interpolate import griddata

In [2]:
### Set up the arrays for interpolation

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
### Read in the limiting magnitudes from grid_stddevs.dat
###  row = one photo-z simulation
###  column = limiting magnitude in ugrizy
points = np.loadtxt( 'grid_stddevs.dat', dtype='float', usecols=(0,1,2,3,4,5))


# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
### Read in the standard deviation in lowest redshift bin from grid_stddevs.dat
values = np.loadtxt( 'grid_stddevs.dat', dtype='float', usecols={6})


# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
### Define test points in 6D-space at which to interpolate.

### Option 0: generic user inputs
# xi = np.asarray( [[25.0, 27.0, 27.0, 26.0, 25.0, 24.0],\
#                   [25.5, 27.5, 27.5, 26.5, 25.5, 24.5],\
#                   [24.5, 26.5, 26.5, 25.5, 24.5, 23.5]], dtype='float' )

### Option 1: slight offset from first few the runs
xi = np.asarray( [points[0]+0.02,\
                  points[1]-0.02,\
                  points[2]+0.05], dtype='float' )
print('Check xi:')
print(points[0],values[0])
print(points[1],values[1])
print(points[2],values[2])
print(xi)

### Option 2: choose a set of limiting magnitudes that are right in the middle.
# mins = np.min(points,axis=0)
# maxs = np.max(points,axis=0)
# mids = mins + (maxs-mins)/2.0
# print('Minimum limiting magnitude in each filter: ',mins)
# print('Maximum limiting magnitude in each filter: ',maxs)
# print('Limiting magnitude in between min/max values: ',mids)
# xi = np.asarray( [mids,mids+0.5,mids-0.5], dtype='float' )


# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
### Quick sanity check on the shapes of our arrays.
### points: ndarray of floats, shape (n, D)
### values: ndarray of float or complex, shape (n,)
### xi: 2-D ndarray of float or tuple of 1-D array, shape (M, D)
print('Check shapes:')
print(points.shape,values.shape,xi.shape)

Check xi:
[26.09 27.38 27.53 26.83 26.05 24.86] 0.0242
[23.15 27.38 27.53 26.83 26.05 24.86] 0.0274
[23.9  27.38 27.53 26.83 26.05 24.86] 0.0266
[[26.11 27.4  27.55 26.85 26.07 24.88]
 [23.13 27.36 27.51 26.81 26.03 24.84]
 [23.95 27.43 27.58 26.88 26.1  24.91]]
Check shapes:
(91, 6) (91,) (3, 6)


In [3]:
### Test the interpolation
### method='cubic' cannot be used as it applies only to 1D and 2D data

### method='nearest'
###  This simply "returns the value at the data point closest to the point of interpolation"
results = griddata(points,values,xi,method='nearest')
print('method = nearest')
print(results)
del results

### method='linear'
results = griddata(points,values,xi,method='linear')
print('method = linear')
print(results)
del results

del points,values,xi

method = nearest
[0.0242 0.0274 0.0266]
method = linear
[nan nan nan]


In [4]:
### I suspect that linear is not working yet because of the 6D space we're working in.
### Try it with just two filters, and see what the results are

points = np.loadtxt( 'grid_stddevs.dat', dtype='float', usecols=(0,1))
values = np.loadtxt( 'grid_stddevs.dat', dtype='float', usecols={6})
xi = np.asarray( [points[0]+0.02,\
                  points[1]-0.02,\
                  points[2]+0.05], dtype='float' )
results = griddata(points,values,xi,method='linear')
print('method = linear')
print(results)
del results
del points,values,xi

method = linear
[0.02518627        nan 0.02677816]
